# introduction to R working environment

# VECTORS AND DATA
# vectors can be created using the c() function
# can include numbers or strings
# vector names are case sensitive

a <- c(1,3,5,7,15,13,11,9)
b <- c(2,4,6,8,10,12,14,16)
c <- c("a", "b", "c", "d", "e", "f")

a
b
c

#some functions for vectors

#algebra
a + b
sqrt(a)
abs(a)
exp(a)
factorial(a)
sum(a)

#statistics
mean(a)
median(a)
var(a)
sd(a)

#ordering
order(a)
sort(a)
range(a)
summary(a)

length(a)

#combine objects as rows (rbind) and as columns (cbind)

d <- cbind(a,b)
e <- rbind(a,b)

d
e

#vectors with repeated values

f <- rep(1:3, each=4, times=3)
f

#visualize elements of a vector

a[3]
a[c(2,4)]

#select a subset of elements of a vector

a.1 <- a[which(a>5)]
a.1

#MATRICES
#A matrix can be generated by the array() function with the dim= argument set to be a vector of length 2. The dimension vector has two elements the number of rows and the number of columns

m1 <- array(1:15, dim=c(3,5))
m1

#to visualize rows, columns or a particular element of a matrix

m1[2,3]
m1[2,]
m1[,3]

#DATA FRAMES
#data frames are the usual way data is stored in R
#it is a set of columns of equal length
#usual convention: columns are variables, rows individuals

x <- c(1:20)
y <- sqrt(x)

x.y <- data.frame(x,y)
colnames(x.y) <- c("x", "sqrtx")
x.y

x.y#to visualize all data objects from the workspace

ls()
objects()

#to delete an object

rm(b)

#class of type of an object

class(a)
class(c)
class(x.y)
class(m1)

#structure of an object

str(a)
str(c)
str(x.y)
str(m1)

#READ AND WRITE FILES

#to write a data frame into a csv file

write.csv(x.y, file="xyEnglish.csv", row.names=FALSE)
write.table(x.y, file="xyEnglish.txt", row.names=FALSE)

#to read the same file into a data frame

x.y.csv <- read.csv(file="xyEnglish.csv", header=TRUE)
x.y.csv

x.y.txt <- read.table(file="xyEnglish.txt", header=TRUE)
x.y.txt

#DATASETS
#R contains a number of example datasets

attitude
summary(attitude)


#PACKAGES
#list of packages available on workspace

library()

#to install a package in R (must be done only once)

install.packages("zoo")

#to use a package in a R session (must be done each time)

library(zoo)

#WORKING DIRECTORY
#to get the working directory

getwd()

#to change working directory (most R editors can do it other ways)

setwd("/home/sallan/Dropbox/00-Rcomm")

#to examine the working directory

dir()


